# Generated by Django 2.2.9 on 2020-01-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotracker', '0002_lot_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotitem',
            name='quantity',
            field=models.FloatField(verbose_name='Количество товара'),
        ),
    ]
