# Generated by Django 2.2.9 on 2020-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotracker', '0003_auto_20200128_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterIndexTogether(
            name='lot',
            index_together={('term_date', 'is_expired')},
        ),
    ]
