# Generated by Django 2.2.9 on 2020-02-05 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotracker', '0004_auto_20200129_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='reference.Organization', verbose_name='Заказчик'),
        ),
        migrations.AlterModelTable(
            name='lotfts',
            table='lots',
        ),
    ]
