# Generated by Django 2.2.9 on 2020-02-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotracker', '0006_filtersetlot'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='params',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
