# Generated by Django 2.2.9 on 2020-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotracker', '0007_filterset_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterset',
            old_name='query',
            new_name='q',
        ),
        migrations.RemoveField(
            model_name='filterset',
            name='current_price_from',
        ),
        migrations.RemoveField(
            model_name='filterset',
            name='current_price_to',
        ),
        migrations.AddField(
            model_name='filterset',
            name='hot_lots',
            field=models.BooleanField(null=True, verbose_name='Горящие лоты'),
        ),
        migrations.AddField(
            model_name='filterset',
            name='price_from',
            field=models.BigIntegerField(null=True, verbose_name='Стоимость (от)'),
        ),
        migrations.AddField(
            model_name='filterset',
            name='price_to',
            field=models.BigIntegerField(null=True, verbose_name='Стоимость (до)'),
        ),
        migrations.AddField(
            model_name='filterset',
            name='without_request',
            field=models.BooleanField(null=True, verbose_name='Без заявок'),
        ),
    ]
