# Generated by Django 2.2.9 on 2020-02-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotracker', '0008_auto_20200207_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='site_type',
            field=models.SmallIntegerField(choices=[(0, 'dxarid'), (1, 'exarid')], null=True, verbose_name='Сайт'),
        ),
    ]
