# Generated by Django 2.2.9 on 2020-02-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotracker', '0009_filterset_site_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtersetlot',
            name='is_displayed',
            field=models.BooleanField(default=False, verbose_name='Отображено?'),
        ),
    ]
