# Generated by Django 2.2.9 on 2020-02-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotracker', '0005_auto_20200205_0056'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_lots',
            field=models.ManyToManyField(related_name='favourite_of_users', to='lotracker.Lot', verbose_name='Сохраненные лоты'),
        ),
    ]
