# Generated by Django 2.2.9 on 2020-02-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_telegram_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
